In [2]:
import tensorflow as tf

In [3]:
print (tf.__version__)

2.16.1


In [4]:
print(tf.test.gpu_device_name())

## Different data structure => 0D, 1D, 2D, more than 2

In [6]:
a = tf.constant(5)
a

<tf.Tensor: shape=(), dtype=int32, numpy=5>

In [7]:
b = tf.constant([1, 2, 3])
b

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [8]:
c = tf.constant([[1, 2, 3], [4, 5, 6]])
c

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [9]:
d = tf.constant([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
d

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]], dtype=int32)>

## Different opperation

In [31]:
a = tf.constant([1, 2]) #1*2
b = tf.constant([3, 4]) #1*2

In [32]:
# sum در جمع ابعاد دو بردار باید با هم برابر باشند
c = tf.add(a, b)
c.numpy()

array([4, 6], dtype=int32)

In [35]:
# subtract
d = tf.subtract(a, b)
d

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([-2, -2], dtype=int32)>

In [15]:
# multiplication دو نوع ضرب : المان به المان و ضرب ماتریسی داریم
a_1 = tf.constant([[1, 2], [3, 4]])
b_1 = tf.constant([[0, 1], [2, 3]])

In [43]:
# element weise ضرب المانی
ew = tf.multiply(a_1, b_1)
ew

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0,  2],
       [ 6, 12]], dtype=int32)>

In [41]:
# matrix multiply در ضرب ماتریسی باید تعداد ستون های ماتریس اول به تعداد سطر های ماتریس دوم برابر باشد
mm = tf.matmul(a_1, b_1)
mm

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 4,  7],
       [ 8, 15]], dtype=int32)>

In [114]:
# devision برای تقسیم باید سایزشان یکی باشد چون المان به المان این کار را انجام میدهد
a = tf.constant([1, 2]) #1*2
b = tf.constant([3, 4]) #1*2
c = tf.constant([5, 0]) #1*2

In [20]:
d = tf.divide(a, b)
d

<tf.Tensor: shape=(2,), dtype=float64, numpy=array([0.33333333, 0.5       ])>

In [24]:
e = tf.divide(b, c)
e

<tf.Tensor: shape=(2,), dtype=float64, numpy=array([0.6, inf])>

In [115]:
# Broadcasting

a = tf.constant([1, 2, 3])
b = tf.constant(4) # => [4, 4, 4]

c = a + b
c

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([5, 6, 7], dtype=int32)>

## reshape

In [116]:
a = tf.constant([1, 2, 3, 4, 5, 6])
a.shape

TensorShape([6])

In [117]:
b = tf.reshape(a, shape=(3, 2, -1))

In [118]:
b.shape

TensorShape([3, 2, 1])

In [119]:
b

<tf.Tensor: shape=(3, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]],

       [[5],
        [6]]], dtype=int32)>

In [120]:
# add dimension اضافه کردن بعد

a = tf.constant([1, 2, 3, 4, 5, 6])
a.shape

TensorShape([6])

In [121]:
b = tf.expand_dims(a, 0)
b.shape

TensorShape([1, 6])

In [122]:
b = tf.expand_dims(a, -1)
b.shape

TensorShape([6, 1])

In [123]:
a

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6], dtype=int32)>

In [124]:
b

<tf.Tensor: shape=(6, 1), dtype=int32, numpy=
array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]], dtype=int32)>

In [125]:
a = tf.constant([[1,2],[3,4]])
a

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [126]:
b = tf.square(a)
b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 1,  4],
       [ 9, 16]], dtype=int32)>

In [127]:
from numpy import float32 # باید تایب اعشاری را مشخص کنیم مگرنه در تقسیم اشتباه میکند
c = tf.sqrt(tf.cast(a, dtype=float32))
c

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1.       , 1.4142135],
       [1.7320508, 2.       ]], dtype=float32)>

## min, max, mean

In [128]:
a = tf.constant([[1,2],[3,4.0]])
a

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

In [129]:
min = tf.reduce_min(a, axis=1) # 0:soton ,1:satr ,none:all
min.numpy()

array([1., 3.], dtype=float32)

In [130]:
max = tf.reduce_max(a, axis=None)
max.numpy()

4.0

In [138]:
# mean with numpy
import numpy as np
a = np.array([[1,2],[3,4.0]])
a.mean()

2.5

In [134]:
avg = tf.reduce_mean(a, axis=0)
avg.numpy()

array([2, 3])

## standard deviation انحراف از معیار

In [139]:
std = tf.math.reduce_std(a) # axis=0,1,None 
std.numpy()

1.118033988749895

In [136]:
sum = tf.reduce_sum(a)
sum.numpy()

10